server:
  port: 8080
  servlet:
    context-path: /andy.blog

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/weblog  
    username: root
    password: 132465
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

# Jwt Security
dashboard: 
  username: admin
  password: admin

jwt:
  issuer: andy-blog
  audience: andy-blog-dashboard
  access:
    expiration:
      time: 43200
    secret: jwt.access.secret
  refresh:
    expiration:
      time: 864000
    secret: jwt.refresh.secret

cors:
  allowed:
    origins: http://localhost:3000
    methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    headers: Authorization, Content-Type
  exposed:
    headers: Authorization